services:
  - type: web
    name: ai-chatbot-backend
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false 